# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
env:
  GITHUB_TOKEN: ${{ secrets.MY_PERSONAL_ACTION_TOKEN }}
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Create Issue From File
        uses: peter-evans/create-issue-from-file@v2.3.1
        with:
          # The GitHub authentication token
          token: ${{ secrets.MY_PERSONAL_ACTION_TOKEN }}
          # The issue number of an existing issue to update
          issue-number: 83
          # The title of the issue.
          title: "Translation tracker"
          # The file path to the issue content.
          content-filepath: "SELI-Platform/lib/translation/english.js"
          # A comma separated list of labels.
          labels: "automated :robot:"
          # A comma separated list of assignees (GitHub usernames).
          assignees: "polusciuro"
          # The name of the project for which a card should be created.
          #project: # optional
          # The name of the project column under which a card should be created.
          #project-column: # optional

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
