name: main

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  issues:
    types: [edited, labeled, unlabeled]
  pull_request:
    types: [opened]
  project_card:
    types: [moved]
env:
  GITHUB_TOKEN: ${{ secrets.MY_PERSONAL_ACTION_TOKEN }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job01: 
#    needs: [assign_one_project]
#    if: github.event_name == 'project_card'
#    name: Auto card labeler
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # NOTE @v2 uses the token as an auth http header. Set it to
          # a Personal Access Token instead of secrets.GITHUB_TOKEN
          # so that tag pushes trigger repo push events.
          token: ${{ secrets.MY_PERSONAL_ACTION_TOKEN }}
      
      - uses: technote-space/auto-card-labeler@v1 
        #GitHub actions that automatically labels Issues or PullRequests based on project card moves
        if: github.event_name == 'project_card' 
        with:
          GITHUB_TOKEN: ${{ secrets.MY_PERSONAL_ACTION_TOKEN }}
            # Config file name.
            #CONFIG_FILENAME: # default is card-labeler.yml

# #     #mail: 
# #       - uses: timheuer/issue-notifier@v1
# #       #GitHub actions that automatically send e-mail when a issue is labeled 
# #         env:
# #           SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
# #         with:
# #           fromMailAddress: 'q4j4v5e8z5w0j0m0@seli-wp4.slack.com'
# #           toMailAddress: 'q4j4v5e8z5w0j0m0@seli-wp4.slack.com'
# #           subject: 'New feature ready to specification'
# #           subjectPrefix: ''
# #           labelsToMonitor: "1 - Planning"
# #           verbose: true
 


#     needs: [triage, assign_one_project]
      - name: commenter by label
        uses: peaceiris/actions-label-commenter@v1.3.2 
#      #Label triggered GitHub Actions for posting a template message, automatically close or reopen issues or pull requests
        if: github.event.action == 'labeled' || github.event.action == 'unlabeled' 
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           config_file: .github/label-commenter-config01.yml

# #comment
#       - name: verbose
#         uses: peter-evans/create-or-update-comment@v1
#         with:
#           token: ${{ secrets.GITHUB_TOKEN }}
#           issue-number: 60
#           body: |
#               *Verbose*
#               event_name: ${{github.event_name }} 
#               event.action: ${{github.event.action}} 
#               event.project_card.id: ${{github.event.project_card.id}} 
#               event.project_card.column_id: ${{github.event.project_card.column_id}} 
#               event.repository.issues_url: ${{github.event.repository.issues_url}} 
#               event.project_card.issues_url: ${{github.event.project_card.issues_url}} 
#               event.project_card.project_url: ${{github.event.project_card.project_url}} 
#               event.project_card.content_id:  ${{github.event.project_card.content_id}} 
#               event.project_card.note:  ${{github.event.project_card.note}} 
#               event.project_card.node_id:  ${{github.event.project_card.node_id}} 
#               github.event_path: ${{github.event_path}} 
# #           reaction-type: '+1'
#       - name: Create Comment - project FUNCTIONAL TEST - card FAILED
#         uses: peter-evans/create-or-update-comment@v1
#         if: |
#           github.event_name == 'project_card' && 
#           github.event.project_card.project_url == 'https://github.com/ecureuill/SELIProject/projects/6' &&
#           github.event.project_card.column_id == 8389382
#         with:
#           token: ${{ secrets.GITHUB_TOKEN }}
#           issue-number: 60
#           body: |
#             :o: @${{ github.event.issue.assignee.login }} your solution didn't pass Functional Test
# #          reaction-type: '+1'

#       - name: Create Comment - project FUNCTIONAL TEST - card SUCCESS
#         uses: peter-evans/create-or-update-comment@v1
#         if: |
#           github.event_name == 'project_card' && 
#           github.event.project_card.project_url == 'https://github.com/ecureuill/SELIProject/projects/6' &&
#           github.event.project_card.column_id == 8389386
#         with:
#           token: ${{ secrets.GITHUB_TOKEN }}
#           issue-number: 60
#           body: |
#             :large_blue_circle: @${{ github.event.issue.assignee.login }} your solution passed Functional Test
# #           reaction-type: '+1'

      - name: Assign 'FEATURE REQUEST' to 'TRIAGE - FEATURE REQUEST'
        uses: srggrs/assign-one-project-github-action@1.2.0
        if: |
          github.event_name == 'issues' && 
          github.event.action == 'labeled' &&  
          contains(github.event.issue.labels.*.name, 'Feature Request')
        with:
          project: 'https://github.com/ecureuill/SELIProject/projects/3'
          column_name: 'NEEDS TRIAGE'
      - name: Assign 'BUG', 'ISSUE',' BUG ON NEXT RELEASE' label to 'TRIAGE - Bugs'
        uses: srggrs/assign-one-project-github-action@1.2.0
        if: |
          github.event_name == 'issues' && 
          github.event.action == 'labeled' &&  (
          contains(github.event.issue.labels.*.name, 'bug') ||
          contains(github.event.issue.labels.*.name, 'bug on next release') ||
          contains(github.event.issue.labels.*.name, 'issues'))
        with:
          project: 'https://github.com/ecureuill/SELIProject/projects/1'
          column_name: 'NEEDS TRIAGE'
        
      - name: Assign '1 - PLANNING' label to 'FEATURE SPECIFICATION'
        uses: srggrs/assign-one-project-github-action@1.2.0
        if: |
          github.event_name == 'issues' && 
          github.event.action == 'labeled' &&  (
          contains(github.event.issue.labels.*.name, '1 - Planning') ||
          contains(github.event.issue.labels.*.name, 'need specification'))
        with:
          project: 'https://github.com/ecureuill/SELIProject/projects/4'
          column_name: 'PENDING FEATURE REQUEST'

      - name: Assign '2 - READY' label to 'DEVELOPMENT CYCLE'
        uses: srggrs/assign-one-project-github-action@1.2.0
        if: |
          github.event_name == 'issues' && 
          github.event.action == 'labeled' &&  
          contains(github.event.issue.labels.*.name, '2 - Ready')
        with:
          project: 'https://github.com/ecureuill/SELIProject/projects/2'
          column_name: 'TO-DO'

      - name: Assign 'need tester' label to 'FUNCTIONALITY TEST CYCLE'
        uses: srggrs/assign-one-project-github-action@1.2.0
        if: |
          github.event_name == 'issues' && 
          github.event.action == 'labeled' &&  
          contains(github.event.issue.labels.*.name, 'need tester')
        with:
          project: 'https://github.com/ecureuill/SELIProject/projects/6'
          column_name: 'TO-DO'

      - name: Assign 'Pull Request' to 'PULL REQUEST CYCLE'
        uses: srggrs/assign-one-project-github-action@1.2.0
        if: |
          github.event_name == 'pull_request' &&
          github.event.action == 'opened'
        with:
          project: 'https://github.com/ecureuill/SELIProject/projects/7'
          column_name: 'In progress'
